title: Flask Alice
author: Liquix
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A mobile-friendly journal for recording psychedelic journeys created with Python and Flask.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
